### ISSUE TITLE
错误反馈

### ISSUE THREAD

**Issue by llyyrr2003** [HITSZ-OpenAuto/AUTO3001B#1]
第一次上机报告中图示位置β计算有误
![5884dfefd61f3609650de2cc87a703fe](https://github.com/HITSZ-OpenAuto/AUTO3001B/assets/147243105/1f746fb8-8761-416a-8fbb-026590b41106)![d8994bce6c4df93793196774b462611d](https://github.com/HITSZ-OpenAuto/AUTO3001B/assets/147243105/3008c606-600f-4719-8ed8-b26d8ac04e30)

**Comment by OliverWu515** [comment]
非常抱歉，之前一直没有看到这个issue。我画了Bode图验证，系统在11rad/s处的幅值约为21.5dB，由20lgβ = 20lg|G(jω_c)|，可算出β约为11.88，你的计算是正确的。
![image](https://github.com/HITSZ-OpenAuto/AUTO3001B/assets/123916865/a98f22c7-042f-4a10-9e27-9ccb3b9ff93e)
非常感谢你的反馈！

**Comment by OliverWu515** [comment]
@lmh12138 这是你上传的实验报告，你打算怎么处理呢

**Comment by lmh12138** [comment]
有错误的话可以将报告先下架或者在PDF上直接修改再上传吧

**Comment by kowyo** [comment]
@llyyrr2003 感谢反馈，已经在 #8 中修复。
